### PR TITLE
Create better documentation

### LINKED ISSUE #11: We need a better documentation for the library
i like this project and i had been using recently to do some stuff with phones, but actually we need a better readable documentation because the library has a ton of stuff. But we lose a lot of time trying to understand how of some of the funtionality works with it because there is no documentation avalaible for it.

### PR DESCRIPTION
**Pull request by yungd1plomat**
Sections:
- **About**
    - [x] Introduction
    - [x] Consulting and Support
    - [x] Licence
- **Getting started**
    - [x] Installation
    - [x] Connecting to device
    - [x] Working with lib
- **Reference**
    - Screen automation
        - [x] Overview screen elements
        - [x] Find elements
        - [x] Click on an element
        - [x] Swipe
        - [x] Type text
        - [x] Send key events
        - [x] Create screenshots
    - Device commands
        - [x] Install and uninstall applications
        - [x] Start and stop applications
        - [x] Push and pull files
        - [x] Run shell commands
        - [x] Forward connection
- **Tutorials**
    - [x] Automate multiple Nox emulators
    

Docs created using [docsify](https://docsify.js.org) and [docsify-darklight-theme](https://docsify-darklight-theme.boopathikumar.me/)

To serve docs use docsify http server
```
# Install docsify
npm i docsify-cli -g

# Serve docs
docsify serve .
```

Or using any other http servers. Example with python:
```Python
python -m SimpleHTTPServer 3000

# OR

python -m http.server 3000
```

### CODE REVIEW

**Comment by wherewhere** [comment]
How can I use Github Package? It said `Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.` when I use my personal token.

**Comment by yungd1plomat** [comment]
> How can I use Github Package? It said `Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.` when I use my personal token.

Do you have telegram?

P.S. you can use GITHUB_TOKEN

**Comment by wherewhere** [comment]
wherewhere/wherewhere7

**Comment by wherewhere** [comment]
Long time no see. 😜

**Comment by yungd1plomat** [comment]
U can preview here https://sharpadb.github.io (I'll change the branch for gh pages after merge)

**Review by wherewhere — APPROVED** [review]

**Pull request merged**
